### ISSUE TITLE
remove extra logo

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-juston-miller/dustybuns#3]
issue: extra logo
page: homepage

how you have it:
![screen shot 2016-03-24 at 1 57 30 pm](https://cloud.githubusercontent.com/assets/7436666/14031162/bf416ade-f1c8-11e5-8fb2-b3ac229e70c8.png)

how it should be:
![screen shot 2016-03-24 at 1 57 46 pm](https://cloud.githubusercontent.com/assets/7436666/14031141/a0fbd67c-f1c8-11e5-92ab-8783d96159a0.png)

option: remove it

**Comment by geekwise-juston-miller** [comment]
@Sramos9191 

This is fix now.
